baseURL = "http://code-zoo.com/"
languageCode = "en-us"
title = "Code-Zoo"
theme = "paperesque"

[[params.topmenu]]
  name = "about"
  url = "about/"

[[params.topmenu]]
  name = "contact"
  url = "contact/"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"